# 此配置文件为多模块多环境下共享，对所有拉取配置的服务生效

# 注册中心
eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      "user.name": ${spring.security.user.name}
      "user.password": ${spring.security.user.password}
      startup: ${random.int}

spring:
  # rabbitmq 相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: felixu
    password: felixu
    publisher-confirms: true
    virtual-host: /
  # redis 相关配置
  redis:
    database: 15
    host: localhost
    port: 6379
    timeout: 6000ms
    # 使用 lettuce 连接池需要引入 commons-pools2 包 group: 'org.apache.commons', name: 'commons-pool2', version: '2.6.0'
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 20
  # session存储
  session:
    store-type: redis
  # spring cache
  cache:
    redis:
      use-key-prefix: true
      cache-null-values: false
      time-to-live: 86400000ms
# Spring Cache Key 的前缀
#      key-prefix: grass
  security:
    user:
      name: felixu
      password: felixu

# feign 请求的日志
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  # 开启熔断
  hystrix:
    enabled: true

# Mybatis Plus 相关全局配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    banner: false

# 暴露心跳相关端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always