# 此配置文件为多模块多环境下共享，对所有拉取配置的服务生效
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  # rabbitmq 相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: felixu
    password: felixu
    publisher-confirms: true
    virtual-host: /
  # redis 相关配置
  redis:
    database: 15
    host: localhost
    port: 6379
    timeout: 6000ms
    # 使用 lettuce 连接池需要引入 commons-pools2 包 group: 'org.apache.commons', name: 'commons-pool2', version: '2.6.0'
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 20
  # session存储
  session:
    store-type: redis
  # spring cache
  cache:
    redis:
      use-key-prefix: true
      cache-null-values: false
      time-to-live: 86400000ms
# Spring Cache Key 的前缀
#      key-prefix: grass
# feign 请求的日志
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

#  hystrix:
#    enabled: true
