eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: felixu
    password: felixu
    publisher-confirms: true
    virtual-host: /